### ISSUE TITLE
consider switching to azurerm, or at least adjust variable spec

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-app-managedenvironment#9]
with workload profile now supported, I'm keen to modify the module back to using azurerm again.

regardless, even if it is kept as azapi, I believe the variable block (module inputs) should be aligned to what azurerm looks like, as close as reasonable, and use snake_casing.

@segraef if you're in agreement I'd like to do this before we publish v0.1.0.

**Comment by segraef** [comment]
Since we're still at 0.1.0 fine with that, it would look differently if we'd have been at 1.0.0 already 😄
